name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    # Etape 1: Tests automatisés
    - name: Navigate to frontend_koolit directory
      run: cd frontend_koolit
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Install dependencies and fix vulnerabilities
      run: |
        npm install leaflet --force
        npm install file-saver --force
        npm audit fix --force
        npm install file-saver --force
        npm install --save-dev @types/file-saver --force
        npm audit fix --force
        npm i --save-dev @types/leaflet --force
        npm audit fix --force

    - name: Run frontend tests
      run: |
        cd ..
        cd Kool-it
        cd frontend_koolit
        npm install --force
      # ng test
      
    - name: Return to root directory
      run: cd ..
      
    - name: Navigate to backend_koolit directory
      run: cd backend_koolit
    
    - name: Run backend tests
      run:  |
        cd backend_koolit
